#!/bin/bash

help_menu() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  help, -h, --help                 Shows this help message"
}

if [[ $# -eq 0 || "$1" == "help" || "$1" == "-h" || "$1" == "--help" ]]; then
    help_menu
    exit 0
fi

command=$1
shift

case "$command" in
    *)
        echo "Error: Invalid option."
        help_menu
        exit 1
        ;;
esac
